# Check https://goreleaser.com/customization/env/
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

# Check https://goreleaser.com/customization/hooks/
before:
  hooks:
  - go mod download

# Check https://goreleaser.com/customization/build/
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
        gomips: hardfloat
    # Run upx after build finished
    #hooks:
    #  post: ./upx.sh

# Check https://goreleaser.com/customization/archive/
archives:
  - name_template: "gwhere_{{ .Version }}_{{ .Os }}_{{ .Arch }}"  
    replacements:
      amd64: x86_64

project_name: gwhere

# Check https://goreleaser.com/customization/homebrew/
brews:
  - folder: Formula
    homepage: "https://github.com/samwheating/gwhere"
    description: "Command line tool for finding a GCS bucket's host project"
    commit_author:
      name: gwhere-releaser
      email: samwheating@gmail.com
    tap:
      owner: samwheating
      name: homebrew-samwheating
